name: Update cms/master

on:
  push:
    branches:
      - test2

jobs:
  update-cms-master:
    name: Merge master into release after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config --local user.email "haducptit@gmail.com"
          git config --local user.name "hatuanduc"
      - name: Merge to main
        run: |
          git fetch --all
          git checkout main
          git merge --no-ff origin/test2
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   - name: merge
    #     uses: mtanzi/action-automerge@v1
    #     id: merge
    #     with:
    #       github_token: ${{ github.token }}
    #       source: 'test2'
    #       target: 'main'
    #       webhook_url: #if present add the Slack webhook