name: Update cms/master

on:
  push:
    branches:
      - 'main'
jobs:
  update-cms-master:
    name: Merge release/test2-* into master
    if: startsWith(github.head_ref, 'release/test2-*')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'test3'
          target: 'main'
          webhook_url: #if present add the Slack webhook